server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userspay?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Danielhatusviana17!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
